[package]
name = "acvus-utils"
version = "0.1.0"
edition = "2024"
license-file.workspace = true

[dependencies]
futures = "0.3.32"
parking_lot = "0.12"
rustc-hash = { workspace = true }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
stacker = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
serde_json = "1"
rustc-hash = { workspace = true }

[lints]
workspace = true
