[package]
name = "acvus-interpreter-test"
version = "0.1.0"
edition = "2024"

[dependencies]
acvus-ast = { path = "../acvus-ast" }
acvus-mir = { path = "../acvus-mir" }
acvus-utils = { path = "../acvus-utils" }
acvus-interpreter = { path = "../acvus-interpreter" }
acvus-extern = { path = "../acvus-extern" }
acvus-ext = { path = "../acvus-ext" }
rustc-hash = { workspace = true }
serde_json = "1.0"

[dev-dependencies]
tempfile = "3"
tokio = { version = "1", features = ["macros", "rt", "time"] }
libtest-mimic = "0.8"
glob = "0.3"

[[test]]
name = "fixtures"
harness = false

[[bench]]
name = "attention"
harness = false

[[bench]]
name = "accum"
harness = false

[[bench]]
name = "mandelbrot"
harness = false
