[package]
name = "acvus-ext-net"
version = "0.1.0"
edition = "2024"

[dependencies]
acvus-extern = { path = "../acvus-extern" }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }

[dev-dependencies]
acvus-ext = { path = "../acvus-ext" }
acvus-interpreter = { path = "../acvus-interpreter" }
acvus-interpreter-test = { path = "../acvus-interpreter-test" }
acvus-mir = { path = "../acvus-mir" }
acvus-ast = { path = "../acvus-ast" }
acvus-utils = { path = "../acvus-utils" }
rustc-hash = { workspace = true }
tokio = { version = "1", features = ["macros", "rt", "net", "io-util", "time"] }
