//! Registrar: Registration interface for ExternFns.
//! ExternFnDef: Macro-generated registration unit.
//! Autoref specialization: Copy/Clone/MoveOnly detection.

use crate::ity::ITy;

// ── Registrar ──────────────────────────────────────────────────────

/// Interface for registering ExternFn types with a host.
pub trait Registrar {
    fn register_drop<T: ITy>(&mut self, drop_fn: fn(T));
    fn register_clone<T: ITy + Clone>(&mut self, clone_fn: fn(&T) -> T);
    fn register_copy<T: ITy + Copy>(&mut self);
}

// ── ExternFnDef ────────────────────────────────────────────────────

/// Trait for structs generated by `#[extern_fn]` macro.
/// Tuples compose for bulk registration.
pub trait ExternFnDef {
    fn register(reg: &mut impl Registrar);
}

macro_rules! impl_extern_fn_def_tuple {
    ($($T:ident),+) => {
        impl<$($T: ExternFnDef),+> ExternFnDef for ($($T,)+) {
            fn register(reg: &mut impl Registrar) {
                $( $T::register(reg); )+
            }
        }
    }
}

impl_extern_fn_def_tuple!(A);
impl_extern_fn_def_tuple!(A, B);
impl_extern_fn_def_tuple!(A, B, C);
impl_extern_fn_def_tuple!(A, B, C, D);
impl_extern_fn_def_tuple!(A, B, C, D, E);
impl_extern_fn_def_tuple!(A, B, C, D, E, F);
impl_extern_fn_def_tuple!(A, B, C, D, E, F, G);
impl_extern_fn_def_tuple!(A, B, C, D, E, F, G, H);

// ── Autoref specialization: Copy/Clone/MoveOnly detection ──────────

/// Zero-sized marker for autoref-based type registration.
///
/// Used by `#[extern_fn]` macro: `(&&&TypeMarker::<T>::new()).__register_type(reg);`
///
/// Rust's method resolution deref chain picks the most specific impl:
/// - `&&TypeMarker<T>`: T: Copy  → register_drop + register_copy
/// - `&TypeMarker<T>`:  T: Clone → register_drop + register_clone
/// - `TypeMarker<T>`:   fallback → register_drop only (move-only)
pub struct TypeMarker<T>(std::marker::PhantomData<T>);

impl<T> TypeMarker<T> {
    pub fn new() -> Self {
        TypeMarker(std::marker::PhantomData)
    }
}

/// Autoref level 1 (highest priority): T: Copy.
pub trait AutoregCopy {
    fn __register_type(&self, reg: &mut impl Registrar);
}

/// Autoref level 2: T: Clone.
pub trait AutoregClone {
    fn __register_type(&self, reg: &mut impl Registrar);
}

/// Autoref level 3 (lowest priority): any T: ITy.
pub trait AutoregMove {
    fn __register_type(&self, reg: &mut impl Registrar);
}

impl<T: ITy + Copy> AutoregCopy for &&TypeMarker<T> {
    fn __register_type(&self, reg: &mut impl Registrar) {
        reg.register_drop::<T>(std::mem::drop);
        reg.register_copy::<T>();
    }
}

impl<T: ITy + Clone> AutoregClone for &TypeMarker<T> {
    fn __register_type(&self, reg: &mut impl Registrar) {
        reg.register_drop::<T>(std::mem::drop);
        reg.register_clone::<T>(T::clone);
    }
}

impl<T: ITy> AutoregMove for TypeMarker<T> {
    fn __register_type(&self, reg: &mut impl Registrar) {
        reg.register_drop::<T>(std::mem::drop);
    }
}
