[package]
name = "acvus-ext"
version = "0.1.0"
edition = "2024"

[dependencies]
acvus-extern = { path = "../acvus-extern" }
acvus-mir = { path = "../acvus-mir" }
acvus-utils = { path = "../acvus-utils" }
futures = "0.3"
sync_wrapper = "1"
rustc-hash = { workspace = true }
regex = "1"
chrono = "0.4"
base64 = "0.22"
percent-encoding = "2"
rust_decimal = "1"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
acvus-interpreter = { path = "../acvus-interpreter" }
acvus-ast = { path = "../acvus-ast" }
tokio = { version = "1", features = ["macros", "rt"] }
